title: Microsoft Bookings Documentation
description: Content to be hosted on MS Learn later
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
